image:
  repository: ghcr.io/hotio/lidarr
  pullPolicy: IfNotPresent
  tag: release-2.11.2.4629

resources:
  limits:
    cpu: 4000m
    memory: 8Gi

lidarrConfig:
  instanceName: Lidarr
  additionalEnvs: []

lidarrNetwork:
  webPort: 30014
  hostNetwork: false

lidarrRunAs:
  user: 568
  group: 568

lidarrStorage:
  config:
    type: ixVolume
    ixVolumeConfig:
      datasetName: config
  additionalStorages: []
